package com.liangxin.platform.common.oa.webservice.getFlowDetailByFlowNumber;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-16T08:58:36.698+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "urn:nader:com/MOBILE", name = "SI_OA_GET_PROCESSDETAIL_ACCORDINGTO_PROCESSNO_Out")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIOAGETPROCESSDETAILACCORDINGTOPROCESSNOOut {

    @WebMethod(operationName = "SI_OA_GET_PROCESSDETAIL_ACCORDINGTO_PROCESSNO_Out", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "findHlhResponse", targetNamespace = "http://webservice.lx.kmss.landray.com/", partName = "parameters")
    public FindHlhResponse siOAGETPROCESSDETAILACCORDINGTOPROCESSNOOut(
            @WebParam(partName = "parameters", name = "findHlh", targetNamespace = "http://webservice.lx.kmss.landray.com/")
                    FindHlh parameters
    ) throws P2Exception;
}
