
package com.liangxin.platform.common.oa.webservice.getFlowDetailByFlowNumber;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-16T08:58:36.686+08:00
 * Generated source version: 3.2.4
 *
 */
public final class SIOAGETPROCESSDETAILACCORDINGTOPROCESSNOOut_HTTPPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:nader:com/MOBILE", "SI_OA_GET_PROCESSDETAIL_ACCORDINGTO_PROCESSNO_OutService");

    private SIOAGETPROCESSDETAILACCORDINGTOPROCESSNOOut_HTTPPort_Client() {
    }



}
