
package com.liangxin.platform.common.oa.webservice.getFlowNumberByFlowId;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-16T09:53:41.649+08:00
 * Generated source version: 3.2.4
 */

@WebFault(name = "Exception", targetNamespace = "http://webservice.lx.kmss.landray.com/")
public class P2Exception extends java.lang.Exception {

    private Exception exception;

    public P2Exception() {
        super();
    }

    public P2Exception(String message) {
        super(message);
    }

    public P2Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public P2Exception(String message, Exception exception) {
        super(message);
        this.exception = exception;
    }

    public P2Exception(String message, Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public Exception getFaultInfo() {
        return this.exception;
    }
}
