
package com.liangxin.platform.common.oa.webservice.getFlowNumberByFlowId;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.transports.http.configuration.HTTPClientPolicy;

import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-16T09:53:41.601+08:00
 * Generated source version: 3.2.4
 */
public class SIOAGETPROCESSNOACCORDINGTOPROCESSIDOut_HTTPSPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:nader:com/MOBILE", "SI_OA_GET_PROCESSNO_ACCORDINGTO_PROCESSID_OutService");

    public SIOAGETPROCESSNOACCORDINGTOPROCESSIDOut_HTTPSPort_Client() {
    }


    public String mainProcess(String pBaseFloderPath, String pFlowId, String pUser, String pPassWord) throws java.lang.Exception {
        URL wsdlURL = new URL("classpath:" + pBaseFloderPath + "getFlowNumberByFlowId.wsdl");
        // URL wsdlURL = SIOAGETPROCESSNOACCORDINGTOPROCESSIDOutService.WSDL_LOCATION;
        SIOAGETPROCESSNOACCORDINGTOPROCESSIDOutService ss = new SIOAGETPROCESSNOACCORDINGTOPROCESSIDOutService(wsdlURL, SERVICE_NAME);
        SIOAGETPROCESSNOACCORDINGTOPROCESSIDOut port = ss.getHTTPSPort();

        Client client = ClientProxy.getClient(port);
        HTTPConduit http = (HTTPConduit) client.getConduit();
        HTTPClientPolicy httpClientPolicy = new HTTPClientPolicy();
        httpClientPolicy.setConnectionTimeout(36000);
        httpClientPolicy.setAllowChunking(false);
        http.setClient(httpClientPolicy);
        http.getAuthorization().setAuthorizationType("NTLM");
        http.getAuthorization().setUserName(pUser);
        http.getAuthorization().setPassword(pPassWord);

        FindReview _siOAGETPROCESSNOACCORDINGTOPROCESSIDOut_parameters = new FindReview();
        _siOAGETPROCESSNOACCORDINGTOPROCESSIDOut_parameters.setArg0(pFlowId);

        FindReviewResponse _siOAGETPROCESSNOACCORDINGTOPROCESSIDOut__return = null;
        _siOAGETPROCESSNOACCORDINGTOPROCESSIDOut__return = port.siOAGETPROCESSNOACCORDINGTOPROCESSIDOut(_siOAGETPROCESSNOACCORDINGTOPROCESSIDOut_parameters);

        return _siOAGETPROCESSNOACCORDINGTOPROCESSIDOut__return.getReturn();
    }
}
