package com.liangxin.platform.common.oa.webservice.getFlowNumberByFlowId;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-16T09:53:41.660+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "SI_OA_GET_PROCESSNO_ACCORDINGTO_PROCESSID_OutService",
                  wsdlLocation = "classpath:oaConfig/webservice/getFlowNumberByFlowId.wsdl",
                  targetNamespace = "urn:nader:com/MOBILE")
public class SIOAGETPROCESSNOACCORDINGTOPROCESSIDOutService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:nader:com/MOBILE", "SI_OA_GET_PROCESSNO_ACCORDINGTO_PROCESSID_OutService");
    public final static QName HTTPSPort = new QName("urn:nader:com/MOBILE", "HTTPS_Port");
    public final static QName HTTPPort = new QName("urn:nader:com/MOBILE", "HTTP_Port");
    static {
        URL url = null;
        try {
            url = new URL("classpath:oaConfig/webservice/getFlowNumberByFlowId.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SIOAGETPROCESSNOACCORDINGTOPROCESSIDOutService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/home/wangxiaochen/FIle/Java/Code/stage/trunk/platform/src/main/resources/oaConfig/webservice/getFlowNumberByFlowId.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SIOAGETPROCESSNOACCORDINGTOPROCESSIDOutService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SIOAGETPROCESSNOACCORDINGTOPROCESSIDOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIOAGETPROCESSNOACCORDINGTOPROCESSIDOutService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SIOAGETPROCESSNOACCORDINGTOPROCESSIDOutService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SIOAGETPROCESSNOACCORDINGTOPROCESSIDOutService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SIOAGETPROCESSNOACCORDINGTOPROCESSIDOutService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SIOAGETPROCESSNOACCORDINGTOPROCESSIDOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIOAGETPROCESSNOACCORDINGTOPROCESSIDOut getHTTPSPort() {
        return super.getPort(HTTPSPort, SIOAGETPROCESSNOACCORDINGTOPROCESSIDOut.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIOAGETPROCESSNOACCORDINGTOPROCESSIDOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIOAGETPROCESSNOACCORDINGTOPROCESSIDOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(HTTPSPort, SIOAGETPROCESSNOACCORDINGTOPROCESSIDOut.class, features);
    }


    /**
     *
     * @return
     *     returns SIOAGETPROCESSNOACCORDINGTOPROCESSIDOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIOAGETPROCESSNOACCORDINGTOPROCESSIDOut getHTTPPort() {
        return super.getPort(HTTPPort, SIOAGETPROCESSNOACCORDINGTOPROCESSIDOut.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIOAGETPROCESSNOACCORDINGTOPROCESSIDOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIOAGETPROCESSNOACCORDINGTOPROCESSIDOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(HTTPPort, SIOAGETPROCESSNOACCORDINGTOPROCESSIDOut.class, features);
    }

}
