package com.liangxin.platform.common.oa.webservice.createFlow;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-15T16:00:39.026+08:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "urn:nader:com/MOBILE", name = "SI_OA_CREATE_PROCESS_Out")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIOACREATEPROCESSOut {

    @WebMethod(operationName = "SI_OA_CREATE_PROCESS_Out", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "addReviewResponse", targetNamespace = "http://webservice.review.km.kmss.landray.com/", partName = "parameters")
    public AddReviewResponse siOACREATEPROCESSOut(
            @WebParam(partName = "parameters", name = "addReview", targetNamespace = "http://webservice.review.km.kmss.landray.com/")
                    AddReview parameters
    ) throws P2Exception;
}
