
package com.liangxin.platform.common.oa.webservice.createFlow;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import org.apache.cxf.endpoint.Client;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.transports.http.configuration.HTTPClientPolicy;
import org.springframework.beans.factory.annotation.Value;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-15T16:00:38.968+08:00
 * Generated source version: 3.2.4
 */
public final class SIOACREATEPROCESSOut_HTTPSPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:nader:com/MOBILE", "SI_OA_CREATE_PROCESS_OutService");

    public SIOACREATEPROCESSOut_HTTPSPort_Client() {
    }

    public AddReviewResponse mainProcess(String pBaseFolderPath, AddReview pAddReview, String pUser, String pPassWord) throws java.lang.Exception {

        URL wsdlURL = new URL("classpath:" + pBaseFolderPath + "createFlow.wsdl");
        // URL wsdlURL = SIOACREATEPROCESSOutService.WSDL_LOCATION;

        SIOACREATEPROCESSOutService ss = new SIOACREATEPROCESSOutService(wsdlURL, SERVICE_NAME);
        SIOACREATEPROCESSOut port = ss.getHTTPSPort();

        Client client = ClientProxy.getClient(port);
        HTTPConduit http = (HTTPConduit) client.getConduit();
        HTTPClientPolicy httpClientPolicy = new HTTPClientPolicy();
        httpClientPolicy.setConnectionTimeout(36000);
        httpClientPolicy.setAllowChunking(false);
        http.setClient(httpClientPolicy);
        http.getAuthorization().setAuthorizationType("NTLM");
        http.getAuthorization().setUserName(pUser);
        http.getAuthorization().setPassword(pPassWord);

        AddReviewResponse _siMOBILEOAOut__return = null;
        try {
            _siMOBILEOAOut__return = port.siOACREATEPROCESSOut(pAddReview);
        } catch (P2Exception e) {
            System.out.println(e.toString());
        }
        return _siMOBILEOAOut__return;
    }

}
