package com.liangxin.platform.common.oa.webservice.createFlow;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-15T16:00:39.033+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "SI_OA_CREATE_PROCESS_OutService",
                  wsdlLocation = "classpath:oaConfig/webservice/createFlow.wsdl",
                  targetNamespace = "urn:nader:com/MOBILE")
public class SIOACREATEPROCESSOutService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:nader:com/MOBILE", "SI_OA_CREATE_PROCESS_OutService");
    public final static QName HTTPSPort = new QName("urn:nader:com/MOBILE", "HTTPS_Port");
    public final static QName HTTPPort = new QName("urn:nader:com/MOBILE", "HTTP_Port");
    static {
        URL url = null;
        try {
            url = new URL("classpath:oaConfig/webservice/createFlow.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SIOACREATEPROCESSOutService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "/oaConfig/webservice/createFlow.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SIOACREATEPROCESSOutService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SIOACREATEPROCESSOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIOACREATEPROCESSOutService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SIOACREATEPROCESSOutService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SIOACREATEPROCESSOutService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SIOACREATEPROCESSOutService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SIOACREATEPROCESSOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIOACREATEPROCESSOut getHTTPSPort() {
        return super.getPort(HTTPSPort, SIOACREATEPROCESSOut.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIOACREATEPROCESSOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIOACREATEPROCESSOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(HTTPSPort, SIOACREATEPROCESSOut.class, features);
    }


    /**
     *
     * @return
     *     returns SIOACREATEPROCESSOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIOACREATEPROCESSOut getHTTPPort() {
        return super.getPort(HTTPPort, SIOACREATEPROCESSOut.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIOACREATEPROCESSOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIOACREATEPROCESSOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(HTTPPort, SIOACREATEPROCESSOut.class, features);
    }

}
