
package com.liangxin.platform.common.oa.webservice.createFlow;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-05-15T16:00:39.012+08:00
 * Generated source version: 3.2.4
 *
 */
public final class SIOACREATEPROCESSOut_HTTPPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:nader:com/MOBILE", "SI_OA_CREATE_PROCESS_OutService");

    private SIOACREATEPROCESSOut_HTTPPort_Client() {
    }

//    public static void main(String args[]) throws java.lang.Exception {
//        URL wsdlURL = SIOACREATEPROCESSOutService.WSDL_LOCATION;
//        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
//            File wsdlFile = new File(args[0]);
//            try {
//                if (wsdlFile.exists()) {
//                    wsdlURL = wsdlFile.toURI().toURL();
//                } else {
//                    wsdlURL = new URL(args[0]);
//                }
//            } catch (MalformedURLException e) {
//                e.printStackTrace();
//            }
//        }
//
//        SIOACREATEPROCESSOutService ss = new SIOACREATEPROCESSOutService(wsdlURL, SERVICE_NAME);
//        SIOACREATEPROCESSOut port = ss.getHTTPPort();
//
//        {
//        System.out.println("Invoking siOACREATEPROCESSOut...");
//        AddReview _siOACREATEPROCESSOut_parameters = null;
//        try {
//            AddReviewResponse _siOACREATEPROCESSOut__return = port.siOACREATEPROCESSOut(_siOACREATEPROCESSOut_parameters);
//            System.out.println("siOACREATEPROCESSOut.result=" + _siOACREATEPROCESSOut__return);
//
//        } catch (P2Exception e) {
//            System.out.println("Expected exception: p2.Exception has occurred.");
//            System.out.println(e.toString());
//        }
//            }
//
//        System.exit(0);
//    }

}
